### ISSUE TITLE
Old: Add form and list of phrases

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/user-stories-test#2]
## Value proposition

**As a** user
**I need** a form to create phrases of my kid
**to be able to** keep them as a memory and to see them in a list

## Description

<img width="200" src=https://user-images.githubusercontent.com/97166533/156576900-d749478e-01f4-42e7-9287-096f716725ad.png />

## Acceptance Criteria

- [ ] There should be a form 
- [ ] There should be an input field of type date
- [ ] There should be a textarea for a phrase
- [ ] Textarea and input field should be required
- [ ] Textarea should have max characters of 250
- [ ] Textarea should have min characters of 0
- [ ] There should be an add button at the end of the form
- [ ] The button should be disabled if there´s no input
- [ ] The button should create a new phrase
- [ ] The inputs should be reseted after each creation
- [ ] The created phrase should be shown underneath the button
- [ ] Each phrase should be a single card
- [ ] The cards of phrases should be scrollable
## Tasks

- [ ] Project setup
- [ ] Global styles
- [ ] components/Button
  - [ ] Storybook
  - [ ] Tests
  - [ ] Styling
- [ ] components/PhraseCard
  - [ ] Storybook
  - [ ] Tests
  - [ ] Styling
- [ ] components/PhraseForm
  - [ ] Storybook
  - [ ] Tests
  - [ ] Styling
  - [ ] useState
    - [ ] Array for the phrases
    - [ ] key for the phrases
    - [ ] e.g. nanoId libary
- [ ] Check accessibility
- [ ] Add to app
