### ISSUE TITLE
Old: Delete a phrase

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/user-stories-test#3]
## Value proposition

**As a** user 
**I need** to delete a phrase 
**to be able to** keep more control of my phrases.

## Description

<img width="200" src=https://user-images.githubusercontent.com/97166533/156596115-5d8c9b56-15ae-49d4-b5a1-4676f8da74be.png />

## Acceptance Criteria

- [ ] There should be a delete button on each card
- [ ] When a user clicks on the button a confirm message should be displayed
- [ ] The user should be able to choose between a cancel or a delete action
- [ ] While the confirm message is open the user is not able to click something else in the app
- [ ] After clicking the confirm message the user should see the other phrases and the form again

## Tasks

- [ ] components/PhraseCard
  - [ ] add a button 
  - [ ] window.confirm 
- [ ] add style components
- [ ] Test on mobile
